fix: Miscellaneous workflow improvements (#11)
Misc workflow improvements

diff --git a/.github/workflows/check-components.yml b/.github/workflows/check-components.yml
--- a/.github/workflows/check-components.yml
+++ b/.github/workflows/check-components.yml
@@ -24,9 +24,15 @@ jobs:
         name: Install jsonschema
         uses: sourcemeta/jsonschema@v15.9.0
       -
-        name: Download schemas
-        id: download-json-schemas
+        name: Validate .components/info.yml
+        env:
+          PROJECT_FILE: .components/info.yml
         run: |
+          if [[ ! -f "${PROJECT_FILE}" ]]; then
+            echo "::error::Missing ${PROJECT_FILE}"
+            exit 1
+          fi
+
           echo "Installing project.schema.json..."
             
           PROJECT_SCHEMA_URL="https://raw.githubusercontent.com/slingshot-pipelines/jsonschemas/main/schemas/project/v1/project.schema.json"
@@ -36,9 +42,12 @@ jobs:
           mkdir "${PROJECT_SCHEMA_DIR}"
           jsonschema install "${PROJECT_SCHEMA_URL}" "${PROJECT_SCHEMA_FILE}"
 
-          echo "project-schema-file=$PROJECT_SCHEMA_FILE" | tee -a "$GITHUB_OUTPUT"
-
           echo ""
+          echo "Validating '${PROJECT_FILE}'..."
+          jsonschema validate "${PROJECT_SCHEMA_FILE}" "${PROJECT_FILE}"
+      -
+        name: Validate components
+        run: |
           echo "Installing component.schema.json..."
           
           COMPONENT_SCHEMA_URL="https://raw.githubusercontent.com/slingshot-pipelines/jsonschemas/main/schemas/component/v1/component.schema.json"
@@ -48,24 +57,6 @@ jobs:
           mkdir "${COMPONENT_SCHEMA_DIR}"
           jsonschema install "${COMPONENT_SCHEMA_URL}" "${COMPONENT_SCHEMA_FILE}"
           
-          echo "component-schema-file=$COMPONENT_SCHEMA_FILE" | tee -a "$GITHUB_OUTPUT"
-      -
-        name: Validate components
-        env:
-          PROJECT_SCHEMA_FILE: ${{ steps.download-json-schemas.outputs.project-schema-file }}
-          COMPONENT_SCHEMA_FILE: ${{ steps.download-json-schemas.outputs.component-schema-file }}
-        run: |
-          PROJECT_FILE=".components/info.yml"
-          
-          echo "::group::Validating $PROJECT_FILE"
-          if [[ -f "${PROJECT_FILE}" ]]; then
-            jsonschema validate "${PROJECT_SCHEMA_FILE}" "${PROJECT_FILE}" --http
-          else
-            echo "::error::Missing ${PROJECT_FILE}"
-            exit 1
-          fi
-          echo "::endgroup::"
-
           COMPONENT_FILES=$(find .components \
             -name 'info.yml' \
             -type f \
@@ -73,13 +64,23 @@ jobs:
             -maxdepth 2 \
             | sort -u)
 
-          FAILED=false
           while IFS='' read -r COMPONENT_FILE && [[ -n "$COMPONENT_FILE" ]]; do
-            echo "::group::Validating $COMPONENT_FILE"
-            jsonschema validate "${COMPONENT_SCHEMA_FILE}" "${COMPONENT_FILE}" --http || FAILED=true
+            echo "Validating $COMPONENT_FILE..."
+            jsonschema validate "${COMPONENT_SCHEMA_FILE}" "${COMPONENT_FILE}"
+            
+            COMPONENT_TYPE=$(cat "$COMPONENT_FILE" | yq '.type')
+            echo "::group::Installing JSON schema for a '$COMPONENT_TYPE' component"
+            COMPONENT_SUBSCHEMA_URL="https://raw.githubusercontent.com/slingshot-pipelines/jsonschemas/main/schemas/component/v1/${COMPONENT_TYPE}.schema.json"
+            COMPONENT_SUBSCHEMA_DIR="${RUNNER_TEMP}/component-subschema-$COMPONENT_TYPE"
+            COMPONENT_SUBSCHEMA_FILE="${COMPONENT_SUBSCHEMA_DIR}/${COMPONENT_TYPE}.schema.json"
+            if [[ -e "$COMPONENT_SUBSCHEMA_FILE" ]]; then
+              echo "Schema already installed"
+            else
+              mkdir "${COMPONENT_SUBSCHEMA_DIR}"
+              jsonschema install "${COMPONENT_SUBSCHEMA_URL}" "${COMPONENT_SUBSCHEMA_FILE}"
+            fi
             echo "::endgroup::"
-          done <<< "$COMPONENT_FILES"
+            
+            jsonschema validate "${COMPONENT_SUBSCHEMA_FILE}" "${COMPONENT_FILE}"
 
-          if [[ "$FAILED" == "true" ]]; then
-            exit 1
-          fi
+          done <<< "$COMPONENT_FILES"
