v2 terragrunt infra workflow

diff --git a/.github/workflows/deploy-terragrunt-infra.yml b/.github/workflows/deploy-terragrunt-infra.yml
--- a/.github/workflows/deploy-terragrunt-infra.yml
+++ b/.github/workflows/deploy-terragrunt-infra.yml
@@ -6,16 +6,18 @@ on:
       COMPONENT:
         required: true
         type: string
+      ENVIRONMENT:
+        required: true
+        type: string
+      TAG:
+        required: true
+        type: string
       TERRAFORM_VERSION:
         type: string
         required: true
       TERRAGRUNT_VERSION:
         type: string
         required: true
-      ALL:
-        type: boolean
-        required: false
-        default: false
       BUILD_CACHE_KEY:
         required: false
         type: string
@@ -36,32 +38,27 @@ defaults:
 
 jobs:
 
-  build-matrix:
-    name: (${{ inputs.COMPONENT }}) terragrunt-matrix
+  parse-component-info:
+    name: (${{ inputs.COMPONENT }}) parse-component-info
     runs-on: ubuntu-latest
     outputs:
-      changes: ${{ steps.build-matrix.outputs.STACKS }}
-      units-dir: ${{ steps.pick-infra-dirs.outputs.units-dir }}
-      stacks-dir: ${{ steps.pick-infra-dirs.outputs.stacks-dir }}
+      UNITS_DIR: ${{ steps.pick-infra-dirs.outputs.units-dir }}
+      STACKS_DIR: ${{ steps.pick-infra-dirs.outputs.stacks-dir }}
     steps:
       -
         uses: actions/checkout@v6
       -
-        name: Components info
-        id: components-info
-        uses: slingshot-pipelines/action-components-info@v1
+        name: Component info
+        id: fetch-component-info
+        uses: slingshot-pipelines/action-component-info@v1
+        with:
+          component: ${{ inputs.COMPONENT }}
       -
         name: Pick infra directories
         id: pick-infra-dirs
         env:
-          COMPONENT: ${{ inputs.COMPONENT }}
-          COMPONENTS_INFO: ${{ steps.components-info.outputs.info }}
-          INFRA_DIR: ${{ fromJSON(steps.components-info.outputs.info)[inputs.COMPONENT].path }}
+          COMPONENT_INFO: ${{ steps.fetch-component-info.outputs.info }}
         run: |
-          COMPONENT_INFO=$(echo "$COMPONENTS_INFO" \
-            | jq -rc --arg component "$COMPONENT" \
-              '.[$component]')
-
           COMPONENT_TYPE=$(echo "$COMPONENT_INFO" | jq -rc '.type')
           if [[ -z "$COMPONENT_TYPE" ]]; then
             >&2 echo "Error determining component type"
@@ -75,32 +72,29 @@ jobs:
           fi
 
           if [[ "$COMPONENT_TYPE" == "lambda" ]]; then
-            echo "units-dir=$COMPONENT_PATH/infra/units" | tee -a "$GITHUB_OUTPUT"
-            echo "stacks-dir=$COMPONENT_PATH/infra/stacks" | tee -a "$GITHUB_OUTPUT"
+            INFRA_SUBPATH=$(echo "$COMPONENT_INFO" | jq -rc '.subpaths.infra')
+            if [[ -z "$INFRA_SUBPATH" ]]; then
+              >&2 echo "Component info.yml missing required field .subpaths.infra"
+              exit 1
+            fi
+
+            echo "units-dir=$COMPONENT_PATH/$INFRA_SUBPATH/units" | tee -a "$GITHUB_OUTPUT"
+            echo "stacks-dir=$COMPONENT_PATH/$INFRA_SUBPATH/stacks" | tee -a "$GITHUB_OUTPUT"
           else
             echo "units-dir=$COMPONENT_PATH/units" | tee -a "$GITHUB_OUTPUT"
             echo "stacks-dir=$COMPONENT_PATH/stacks" | tee -a "$GITHUB_OUTPUT"
           fi
-      -
-        name: Detect changes
-        uses: slingshot-pipelines/action-terragrunt/matrix@v0
-        id: build-matrix
-        with:
-          UNITS_DIR: ${{ steps.pick-infra-dirs.outputs.units-dir }}
-          STACKS_DIR: ${{ steps.pick-infra-dirs.outputs.stacks-dir }}
-          TRIGGER_ALL: ${{ inputs.ALL }}
 
   apply:
+    needs: [parse-component-info]
     name: (${{ inputs.COMPONENT }}) terragrunt-apply
-    needs: 
-      - build-matrix
-    if: ${{ (needs.build-matrix.outputs.changes || '') != '[]' }}
-    uses: slingshot-pipelines/workflows/.github/workflows/terragrunt-apply.yml@terragrunt-apply/v0
+    uses: slingshot-pipelines/workflows/.github/workflows/terragrunt-apply.yml@terragrunt-apply/v1
     with:
       COMPONENT: ${{ inputs.COMPONENT }}
+      STACK: ${{ inputs.ENVIRONMENT }}
+      TAG: ${{ inputs.TAG }}
       TERRAGRUNT_VERSION: ${{ inputs.TERRAGRUNT_VERSION }}
       TERRAFORM_VERSION: ${{ inputs.TERRAFORM_VERSION }}
-      STACKS_DIR: ${{ needs.build-matrix.outputs.stacks-dir }}
-      STACKS: ${{ needs.build-matrix.outputs.changes }}
+      STACKS_DIR: ${{ needs.parse-component-info.outputs.STACKS_DIR }}
       BUILD_CACHE_KEY: ${{ inputs.BUILD_CACHE_KEY }}
       BUILD_CACHE_PATH: ${{ inputs.BUILD_CACHE_PATH }}
